"""Cold-start test: can a model recommend tracks that had no listens in training?

A seeded random share of the training tracks is held out: every listen of those tracks is
left out when tt_content is trained. Models are then scored on the held-out tracks only,
beside two references that need no training:

  content_sim  the held-out tracks whose features are closest to the average of what the user played
  random       the held-out tracks in an order unrelated to plays or content

  val     trains tt_content and prints the val results. Writes nothing.
  report  the same, scored on val and test. Writes reports/coldstart.md and saves the vectors.

Usage: python -m m4a_rec.coldstart val | report
"""
from __future__ import annotations

import sys

import numpy as np
import scipy.sparse as sp

from .config import load_config
from .evaluate import score
from .features import load_blocks
from .interactions import build, load_train
from .reporting import metric_tables, stable_json
from .retrieval import fit, recommend, save

RANDOM_DIM = 32  # length of the vectors behind the random reference


def held_out(n_tracks: int, fraction: float, seed: int) -> np.ndarray:
    """Sorted column indices of a seeded random `fraction` of the tracks."""
    rng = np.random.default_rng(seed)
    return np.sort(rng.choice(n_tracks, size=round(fraction * n_tracks), replace=False))


def without(matrix: sp.csr_matrix, tracks: np.ndarray) -> sp.csr_matrix:
    """A copy of the matrix with the columns in `tracks` emptied."""
    keep = np.ones(matrix.shape[1], dtype=matrix.dtype)
    keep[tracks] = 0
    out = (matrix @ sp.diags(keep)).tocsr()
    out.eliminate_zeros()
    return out


def unit(x: np.ndarray) -> np.ndarray:
    """Each row scaled to length 1; an all-zero row stays zero."""
    length = np.linalg.norm(x, axis=1, keepdims=True)
    return (x / np.where(length > 0, length, 1)).astype(np.float32)


def content_sim_vecs(matrix: sp.csr_matrix, blocks: dict[str, np.ndarray]) -> tuple[np.ndarray, np.ndarray]:
    """User and track vectors whose dot product is the content similarity, with no training.

    A track's vector is its audio, lyrics and genre features side by side, each scaled to
    length 1 first so the three kinds count equally. A user's vector is the direction of
    the average of the tracks they played in `matrix`.
    """
    tracks = unit(np.concatenate([unit(blocks[name]) for name in ("audio", "lyrics", "genres")], axis=1))
    played = (matrix > 0).astype(np.float32)
    return unit(played @ tracks), tracks


def random_vecs(n_users: int, n_tracks: int, seed: int) -> tuple[np.ndarray, np.ndarray]:
    """Random user and track vectors: their dot products rank tracks with no information at all."""
    rng = np.random.default_rng(seed)
    return (
        rng.standard_normal((n_users, RANDOM_DIM), dtype=np.float32),
        rng.standard_normal((n_tracks, RANDOM_DIM), dtype=np.float32),
    )


def render(cold: dict, everything: dict, n_held: int, c: dict, splits: tuple[str, ...], ks: list[int]) -> str:
    """`cold` and `everything` map model name to {split: metrics}."""
    L = [
        "# Phase 4 cold start",
        "",
        "Generated by `python -m m4a_rec.coldstart report`. Do not edit by hand; rerun instead.",
        "",
        f"{n_held:,} tracks ({c['fraction']:.0%} of the training tracks, seed {c['seed']}) were held out:",
        "tt_content was trained without any of their listens. Popularity, item-kNN and ALS cannot",
        "recommend a track with no listens, so they score 0 on the first set of tables.",
        "",
        "In the first set only the held-out tracks can be recommended and only they count as",
        "relevant, and coverage is the share of held-out tracks. The second set scores the same",
        "tt_content model on all tracks, for comparison with `reports/retrieval.md`.",
        "",
    ]
    L += metric_tables(cold, ks, splits, prefix="Held-out tracks only: ")
    L += metric_tables(everything, ks, splits, prefix="All tracks: ")
    return "\n".join(L)


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    if argv not in (["val"], ["report"]):
        print(__doc__)
        return 2
    cfg = load_config()
    t, c, processed = cfg["twotower"], cfg["cold_start"], cfg["paths"]["processed"]
    inter = build(load_train(processed / "splits", t["train_splits"]), "log")
    blocks = load_blocks(processed / "features.npz", inter.track_ids.to_list())
    held = held_out(inter.matrix.shape[1], c["fraction"], c["seed"])
    held_ids = inter.track_ids.gather(held).to_list()

    def cold(vecs, split):
        return score(recommend(inter, *vecs, t["n_recs"], candidates=held), split, only_tracks=held_ids)

    params = t["chosen"]["tt_content"]
    print(f"tt_content {params}, {len(held):,} tracks held out", flush=True)
    result = fit(
        inter,
        np.concatenate(list(blocks.values()), axis=1),
        t["models"]["tt_content"],
        params,
        t,
        lambda u, v: cold((u, v), "val"),
        exclude_tracks=held,
        log=lambda m: print(m, flush=True),
    )
    vecs = {
        "tt_content": (result["user_vecs"], result["track_vecs"]),
        "content_sim": content_sim_vecs(without(inter.matrix, held), blocks),
        "random": random_vecs(*inter.matrix.shape, c["seed"]),
    }
    splits = ("val",) if argv == ["val"] else ("val", "test")
    cold_results = {name: {split: cold(v, split) for split in splits} for name, v in vecs.items()}
    everything = {
        "tt_content": {split: score(recommend(inter, *vecs["tt_content"], t["n_recs"]), split) for split in splits}
    }
    text = render(cold_results, everything, len(held), c, splits, cfg["metrics"]["ks"])
    if argv == ["val"]:
        print(text)
    else:
        reports = cfg["paths"]["reports"]
        save(processed / "models" / "tt_content", inter, result, params)
        (reports / "coldstart.json").write_text(stable_json({"cold": cold_results, "all": everything}))
        (reports / "coldstart.md").write_text(text)
        print(f"wrote {reports / 'coldstart.md'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
